# Dependencies
markdown:         kramdown
highlighter:      rouge

sass:
  style: compressed

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Salil
description:      'A machine learning enthusiast with interests in Computer Vision, Deep Learning, and Robotics'
url:              https://salildabholkar.github.io/
baseurl:          https://salildabholkar.github.io/

author:
  name:           'Salil Dabholkar'
  url:            https://salildabholkar.github.io/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/salildabholkar/
